name: "Helm Chart Testing"
description: "Install the Helm chart-testing tool"
author: "The Helm authors"
branding:
  color: blue
  icon: anchor
inputs:
  version:
    description: "The chart-testing version to install (default: v3.5.0)"
    default: v3.5.0
runs:
  using: composite
  steps:
    - run: "$GITHUB_ACTION_PATH/ct.sh --version ${{ inputs.version }}"
      shell: bash
