name: "Helm Chart Testing"
description: "Install the Helm chart-testing tool"
author: "The Helm authors"
branding:
  color: blue
  icon: anchor
inputs:
  version:
    description: "The chart-testing version to install (default: 3.12.0)"
    required: false
    default: '3.14.0'
  yamllint_version:
    description: "The yamllint version to install (default: 1.27.1)"
    required: false
    default: '1.33.0'
  yamale_version:
    description: "The yamale version to install (default: 4.0.4)"
    required: false
    default: '6.0.0'
runs:
  using: composite
  steps:
    - uses: sigstore/cosign-installer@d7d6bc7722e3daa8354c50bcb52f4837da5e9b6a # v3.8.1
    - run: |
        cd $GITHUB_ACTION_PATH \
        && ./ct.sh \
            --version ${{ inputs.version }} \
            --yamllint-version ${{ inputs.yamllint_version }} \
            --yamale-version ${{ inputs.yamale_version }}
      shell: bash
