name: "Helm Chart Testing"
description: "Install the Helm chart-testing tool"
author: "The Helm authors"
branding:
  color: blue
  icon: anchor
inputs:
  verify_blob:
    description: "determines whether the download blob should be verified (default: true)"
    required: false
    default: 'true'
  version:
    description: "The chart-testing version to install (default: 3.12.0)"
    required: false
    default: '3.12.0'
  yamllint_version:
    description: "The yamllint version to install (default: 1.27.1)"
    required: false
    default: '1.33.0'
  yamale_version:
    description: "The yamale version to install (default: 4.0.4)"
    required: false
    default: '4.0.4'
runs:
  using: composite
  steps:
    - uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da # v3.7.0
      if: ${{ inputs.verify_blob != 'false' }}
    - run: |
        cd $GITHUB_ACTION_PATH \
        && ./ct.sh \
            --verify-blob ${{ inputs.verify_blob }} \
            --version ${{ inputs.version }} \
            --yamllint-version ${{ inputs.yamllint_version }} \
            --yamale-version ${{ inputs.yamale_version }}
      shell: bash
