name: "Helm Chart Testing"
description: "Run the Helm chart-testing tool"
author: "The Helm authors"
branding:
  color: blue
  icon: anchor
inputs:
  image:
    description: "The chart-testing Docker image to use (default: quay.io/helmpack/chart-testing:v3.0.0-rc.1)"
  config:
    description: "The relative path to the chart-testing config file"
  command:
    description: "The chart-testing command to run"
    required: true
  kubeconfig:
    description: "The path to the kube config file"
outputs:
  changed:
    description: "Whether or not charts have changed (true/false)"
runs:
  using: "node12"
  main: "main.js"
