name: "Helm Chart Testing"
description: "Install the Helm chart-testing tool"
author: "The Helm authors"
branding:
  color: blue
  icon: anchor
inputs:
  version:
    description: "The chart-testing version to install (default: 3.9.0)"
    required: false
    default: '3.9.0'
  yamllint_version:
    description: "The yamllint version to install (default: 1.27.1)"
    required: false
    default: '1.27.1'
  yamale_version:
    description:  "The yamale version to install (default: 3.0.4)"
    required: false
    default: '3.0.4'
runs:
  using: composite
  steps:
    - uses: sigstore/cosign-installer@11086d25041f77fe8fe7b9ea4e48e3b9192b8f19 # v3.1.2
    - run: |
        cd $GITHUB_ACTION_PATH \
        && ./ct.sh \
            --version ${{ inputs.version }} \
            --yamllint-version ${{ inputs.yamllint_version }} \
            --yamale-version ${{ inputs.yamale_version }}
      shell: bash
