name: "Helm Chart Testing"
description: "Install the Helm chart-testing tool"
author: "The Helm authors"
branding:
  color: blue
  icon: anchor
inputs:
  token:
    description: "The token used to authenticate when fetching chart-testing release. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting."
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}
  version:
    description: "The chart-testing version to install (default: v3.8.0)"
    required: false
    default: v3.8.0
  yamllint_version:
    description: "The yamllint version to install (default: 1.27.1)"
    required: false
    default: '1.27.1'
  yamale_version:
    description:  "The yamale version to install (default: 3.0.4)"
    required: false
    default: '3.0.4'
runs:
  using: composite
  steps:
    - uses: sigstore/cosign-installer@c3667d99424e7e6047999fb6246c0da843953c65 # v3.0.1
    - run: |
        cd $GITHUB_ACTION_PATH \
        && ./ct.sh \
            --token ${{ inputs.token }} \
            --version ${{ inputs.version }} \
            --yamllint-version ${{ inputs.yamllint_version }} \
            --yamale-version ${{ inputs.yamale_version }}
      shell: bash
