name: Push Workflow

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Release branch
        uses: unguiculus/release-branch-action
        with:
          build_cmd: npm install && npm run build
          paths_to_add: node_modules,lib
          paths_to_remove: src,package-lock.json,package.json,tsconfig.json
          token: ${{ secrets.GITHUB_TOKEN }}
